---

# create networks if do not exists
- include: network-create.yml

# create source
- include: vm-create.yml
  tags: build

- include: vm-clone.yml
  tags: build

- include: wait-for-access.yml
  tags: build

#- include: snapshot-create.yml
#  tags: build

- include: install-common.yml
- include: snapshot-create-update.yml
