---


# create networks if do not exists
- include: network-create.yml

# create source
- include: vm-create.yml
  tags: build
# after creation source is running to check if it is finished

- include: vm-clone.yml
  when: "'source' in groups.keys()"
  tags: build
  # source is shutdown and all nodes are cloned and shut down with the same ipaddress

- include: vm-cloned-conf-network.yml
  when: "'source' in groups.keys()"
  tags: build

- include: wait-for-access.yml
  tags: build

#- include: snapshot-create.yml
#  tags: build

- include: install-common.yml
- include: snapshot-create.yml snapshot_name=01-after-update
