---

- name: create the qcow2 images
  hosts: localhost ansible_connection=local

  #we are working only on the qcow2 images... so no info about vms
  gather_facts: no

  vars:
    source_ipaddress: 

  roles:
      #external role from vm-create project
      - vm-create
