---
volume_pool: ssd-virt
volumes_location: "/virt/virtuals"

project: virtuale
dns_resolver: 192.168.1.1

#vm_os_type: centos-7.3
vm_distribution: debian
vm_codename: buster #vm_release: 9 = stretch


#for centos image size is not working
vm_disk_size: "8G"

vm_memory: 2048
vm_cpus: 2

#each node will have its own port with increment 1 according to list

# how the virtual network is to be connected to the physical LAN: nat, route, open, ...
forward_mode: nat
#network definition
networks:
  mgmt:
    gateway: 192.168.82.1
    netmask: 255.255.255.0
  prod:
    gateway: 192.168.83.1
    netmask: 255.255.255.0

#list of virtual machines
#if you do not want to use source:
#1) name of source change from source to the short name of the first node
#   and ip change also to first_ip_address
#2) generate the invetory file using make_inventory_file.py

source: source
source_ip_address: 5

nodes:
  - node1
  - node2
  - node3
first_ip_address: 11
#all other ip addresses will be with the step 1
#derived from network_gateway and first_ip_address

domain: "{{project}}.mate.solutions"

dns_planned: False

additional_packages:
  - vim
  - ranger

proxy_env:
  http_proxy: "http://192.168.1.1:3128"
  https_proxy: "https://192.168.1.1:3128"

ntp_config_server: 192.168.1.1
timezone: "Europe/Bratislava"
