---

- name: create the directory for network xml files
  file:
    path: "{{playbook_dir}}/roles/network-create/templates/xml/networks"
    owner: martin
    group: martin
    mode: 0755
    state: directory

- name: create xml for each network
  template:
    src: virt-network.xml.j2
    dest: "{{playbook_dir}}/roles/network-create/templates/xml/networks/{{project}}-{{item.key}}.xml"
    owner: martin
    group: martin
    mode: 0644
  with_dict: "{{networks}}"
