---
# we are working only with localhost
# default state of master is running - has to be stopped
#only if cloned nodes do not exist
# so at first which nodes we have
# test them if they are

- name: get all virtual machines from the pool
  virt:
    command: "list_vms"
  register: vms

- name: only if cloned nodes do not exist
  set_fact:
     missing_node: true
     source_full_ip_address: "{{networks['mgmt'].gateway[:-1]}}{{source_ip_address}}"
  when: item not in vms
  with_items: "{{nodes}}"

- name: DEBUG missing node
  debug:
    var: missing_node

- name: preparation and cloning itself
  block:
  - name: wait for server to reboot and report SSH availability
    local_action: wait_for host={{source_full_ip_address}} state=started port=22 delay=0 timeout=1000

  - name: shutdown source
    virt:
        name: "{{project}}-{{source}}"
        state: shutdown

  - name: master domain has to be stopped before cloning
    local_action: wait_for host={{source_full_ip_address}} port=22 state=stopped

  - name: clone machine
    command: "virt-clone --original {{project}}-{{source}} --name {{project}}-{{item}}
              --file /data/virt/{{project}}-{{item}}.qcow2"
    with_items: "{{nodes}}"

  - name: start all nodes
    virt:
      name: "{{project}}-{{item}}"
      state: running
    with_items: "{{nodes}}"

  when: missing_node
