---

- name: create directory for run script in step virt-builder for each node
  file:
    path: "{{inventory_dir}}/roles/create/templates/{{item}}"
    owner: martin
    group: martin
    mode: 0755
    state: directory
  with_items: "{{nodes}}"

- name: create the directory for network xml files
  file:
    path: "{{inventory_dir}}/roles/create/templates/xml/networks"
    owner: martin
    group: martin
    mode: 0755
    state: directory

- name: DEBUG Looping over Subelements in networks
  debug:
    msg: "Network={{item.0.name}} gateway={{item.1.gateway}} netmask={{item.1.netmask}}"
  with_subelements:
    - "{{networks}}"
    - config
  tags: debug

- name: Set vm_os_type from distribution and version
  set_fact:
      vm_os_type: "{{vm_distribution}}-{{vm_release}}"

# it is possible to prepare also nested loops but we lost indexing
# possible also to change the structure of variables for the node list
# temporary solution - each network will have the separate part for nodes's
# interfaces ens3, ens4,....

- name: prepare run script from template for virtuals all network interfaces
  template:
    src: "interface-{{vm_distribution}}-all.j2"
    dest: "{{inventory_dir}}/roles/create/templates/{{item.1}}/post-install-all.sh"
                                 # indexed #
    owner: martin
    group: martin
    mode: 0644
  with_indexed_items: "{{nodes}}"

- name: create xml for each network
  template:
    src: virt-network.xml
    dest: "{{inventory_dir}}/roles/create/templates/xml/networks/{{project}}-{{item.0.name}}.xml"
    owner: martin
    group: martin
    mode: 0644
  with_subelements:
    - "{{networks}}"
    - config
