---

- name: prepare directory for preseed.cfg script
  file:
    path: "{{playbook_dir}}/roles/vm-create/templates/{{project_source}}"
    owner: martin
    group: martin
    mode: 0644
    state: directory

- name: prepare preseed.cfg script from template
  template:
    src: "preseed-{{vm_distribution}}-{{vm_codename}}.cfg.j2"
    dest: "{{playbook_dir}}/roles/vm-create/templates/{{project_source}}/preseed.cfg"
    owner: martin
    group: martin
    mode: 0644

- name: list virtual machine volumes
  command: "ls {{volumes_location}}"
  register: disks
  changed_when: "disks.rc != 0"

- name: create disk
  command: "virsh vol-create-as --pool {{volume_pool}} --name {{project_source}}.qcow2
           --capacity {{vm_disk_size}} --format qcow2"
  when: project_source not in disks.stdout

- name: get all virtual machines from the pool
  virt:
    command: "list_vms"
  register: vms

- name: create vm install_location "{{install_location}}"
  command: "virt-install  --location {{install_location}}
        --name {{project_source}}
        --vcpus {{vm_cpus}},maxvcpus={{vm_cpus}} --ram {{vm_memory}}
        --network network={{project}}-mgmt
        --disk {{volumes_location}}/{{project_source}}.qcow2
        --initrd-inject={{playbook_dir}}/roles/vm-create/templates/{{project_source}}/preseed.cfg
        --extra-args=auto --graphics vnc --noautoconsole --wait=-1"
  when: project_source not in vms.list_vms

- name: DELETE directory for preseed.cfg script from template
  file:
    path: "{{playbook_dir}}/roles/vm-create/templates/{{project_source}}"
    state: absent

- name: list already defined virtual machine interfaces
  command: "virsh domiflist --domain {{project_source}}"
  register: vm_interfaces
  changed_when: "vm_interfaces.rc != 0"

- name: attach new interace to the additional networks
  command: "virsh attach-interface --domain {{project_source}} --type network
            --source {{project}}-{{item.key}} --config --live"
  when: item.key not in vm_interfaces.stdout
  with_dict: "{{networks}}"
