---

- name: Set vm_os_type from distribution and version
  set_fact:
      vm_os_type: "{{vm_distribution}}-{{vm_release}}"

# it is possible to prepare also nested loops but we lost indexing
# possible also to change the structure of variables for the node list
# temporary solution - each network will have the separate part for nodes's
# interfaces ens3, ens4,....

- name: create the directory for node network files
  file:
    path: "{{inventory_dir}}/roles/vm-clone/templates/{{item.1}}"
    owner: martin
    group: martin
    mode: 0755
    state: directory
  with_indexed_items: "{{nodes}}"

- name: prepare run script from template for virtuals all network interfaces
  template:
    src: "interface-{{vm_distribution}}-all.j2"
    dest: "{{inventory_dir}}/roles/vm-clone/templates/{{item.1}}/post-install-all.sh"
                                 # indexed #
    owner: martin
    group: martin
    mode: 0644
  with_indexed_items: "{{nodes}}"
