---
- name: debug the hostname variable
  debug:
    var: inventory_hostname
  tags: debug

- name: change the hostname in hostname
  hostname:
    name: "{{inventory_hostname}}"

# /etc/hosts has to be updated separately
- name: replace the IP 127.0.0.1 and the hostname localhost in the hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1\s*localhost'
    line: "127.0.0.1       localhost"

- name: delete the IP 127.0.1.1 and the hostname in the hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.1.1'
    state: absent

- name: test if hosts file already exists
  shell: grep {{groups.nodes[0]}} /etc/hosts || true
  register: hosts_test

- name: additional lines with prepared nodes and their ip addresses to hosts file
  include: t-02-nodes-list-in-etc_hosts.yml
  when: hosts_test.stdout|length == 0
