---

- name: change the local timezone
  command: timedatectl set-timezone Europe/Bratislava

- name: install ntp package debian
  apt:
    name: ntp
    state: present

# customize the /etc/ntp.conf file

- name: Hosts on local network are less restricted - restrict 192.168.1.0
  lineinfile:
    dest: /etc/ntp.conf
    regexp: 'restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap'
    line: 'restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap'

#this lines should be commented:
#server 0.centos.pool.ntp.org iburst
- name: comment all existing centos.pool.ntp servers
  replace:
    dest: /etc/ntp.conf
    regexp: '^(server .*pool\.ntp\.org iburst)$'
    replace: '#\1'

- name: insert turris ntp server
  lineinfile:
    dest: /etc/ntp.conf
    regexp: 'server 192.168.1.1'
    line: 'server 192.168.1.1'

# in debian needed restart
- name: start and enable the ntpd service
  systemd:
    name: ntp
    state: restarted
    enabled: yes
