---
#instal additional packages with apt and pip

#DEBIAN
- block:
  - name: install additional packages debian
    apt:
      name: "{{item}}"
      state: present
    with_items: "{{additional_packages}}"
    when: additional_packages is defined

- name: copy the own vimrc config file
  copy:
    src: /home/martin/.vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0640
  tags: "vimrc"
