---
#instal additional packages with apt and pip
#CENTOS
- block:
  - name: install additional packages with yum centos
    yum:
      name: "{{item}}"
      state: present
    with_items: "{{additional_packages}}"
    when: additional_packages is defined
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#DEBIAN
- block:
  - name: install additional packages debian
    apt:
      name: "{{item}}"
      state: present
    with_items: "{{additional_packages}}"
    when: additional_packages is defined
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
