---
#resizing on the host
- name: DEBUG ({{vm_image_size[:-1]}} > 6)
  debug:
    var: vm_image_size[:-1]
  tags: debug

- name: grab the info about the virtual machines -all
  local_action: virt command=info
  register: virt_info

- name: DEBUG the basic variable virt_info
  debug:
    msg: "virt_info is {{virt_info}}"
  tags: debug

- name: shutdown
  shell: sleep 2 && /sbin/shutdown -P now
  async: 1
  poll: 0
  ignore_errors: true
  when: virt_info["{{project}}.{{ inventory_hostname_short }}"]["state"] == "running"

- name: wait for all server shutdown
  local_action: wait_for host={{ansible_host}} state=stopped port=22 delay=10 timeout=300

- name: qemu-img resize {{ vm_image_dir }}/{{ project }}.{{ inventory_hostname_short }}.qcow2 {{ vm_image_size }}
  local_action: command qemu-img resize "{{ vm_image_dir }}/{{ project }}.{{ inventory_hostname_short }}.qcow2" "{{ vm_image_size }}"


#resizing on the vms:
- name: start the vm
  local_action: virt name={{ project }}.{{ inventory_hostname_short }} state=running

- name: wait for all server running
  local_action: wait_for host={{ ansible_host }} state=started port=22 delay=5 timeout=300

- name: copy the config file for the disk layout
  copy:
    src: templates/sda-info.txt
    dest: /root/sda-info.txt
    owner: root
    group: root
    mode: 0644

- name: enlarge the disk with the command sfdisk /dev/hdd -O sda-info.txt
  shell: sfdisk -f -O PT.save /dev/sda < /root/sda-info.txt
  ignore_errors: yes

- name: reboot
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
#  when: update_realised.changed == true

- name: wait for all server running
  local_action: wait_for host={{ansible_host}} state=started port=22 delay=10 timeout=300
  tags: after_sfdisk

- name: pvresize /dev/sda2
  command: pvresize /dev/sda2
  tags: after_sfdisk

- name:  lvextend -l +100%FREE /dev/mapper/cl-root
  command:  lvextend -l +100%FREE /dev/mapper/cl-root
  tags: after_sfdisk

- name:  XFS file systems must be mounted to be resized so>  xfs_growfs /
  command: xfs_growfs /
  tags: after_sfdisk
