---

- name: reboot
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
#  when: update_realised.changed == true

- name: DEBUG display the variable inventory_hostname
  debug:
    var: inventory_hostname
  tags: debug

- name: wait for server to reboot and report SSH availability
  local_action: wait_for host={{ansible_host}} state=started port=22 delay=5 timeout=300
#  when: update_realised.changed == true




